# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 273)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 邮箱输入框
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        # 邮箱标签
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(134, 52, 31, 16))
        self.label.setObjectName("label")

        # 验证码标签
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(124, 92, 41, 16))
        self.label_2.setObjectName("label_2")

        # 验证码输入框
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 90, 113, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")

        # 注册按钮
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")

        # 发送验证码按钮
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        # 密码标签
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(134, 132, 31, 16))
        self.label_3.setObjectName("label_3")

        # 密码输入框
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 130, 113, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 绑定按钮事件
        self.pushButton_2.clicked.connect(self.on_send_verification)  # 绑定发送验证码按钮
        self.pushButton.clicked.connect(self.on_register)  # 绑定注册按钮

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "邮箱："))
        self.label_2.setText(_translate("MainWindow", "验证码："))
        self.pushButton.setText(_translate("MainWindow", "注册"))
        self.pushButton_2.setText(_translate("MainWindow", "发送验证码"))
        self.label_3.setText(_translate("MainWindow", "密码："))

    # 发送验证码的方法
    def on_send_verification(self):
        email = self.lineEdit.text().strip()
        if not email:
            QMessageBox.warning(None, "错误", "请先输入邮箱")
            return
        try:
            resp = requests.post("http://127.0.0.1:5000/send_register_email", json={"email": email}, timeout=5)
        except Exception as e:
            QMessageBox.warning(None, "网络错误", f"无法连接服务器：{e}")
            return

        if resp.status_code == 200:
            j = resp.json()
            if j.get("ok"):
                QMessageBox.information(None, "已发送", "验证码已发送，请检查邮箱")
            else:
                QMessageBox.warning(None, "发送失败", j.get("message", "未知错误"))
        else:
            QMessageBox.warning(None, "发送失败", f"HTTP {resp.status_code}")

    # 注册的方法
    def on_register(self):
        email = self.lineEdit.text().strip()
        code = self.lineEdit_2.text().strip()
        password = self.lineEdit_3.text()

        if not email or not code or not password:
            QMessageBox.warning(None, "错误", "邮箱/验证码/密码都不能为空")
            return

        try:
            resp = requests.post("http://127.0.0.1:5000/register", json={"email": email, "password": password},
                                 timeout=5)
        except Exception as e:
            QMessageBox.warning(None, "网络错误", f"无法连接服务器：{e}")
            return

        if resp.status_code == 200:
            j = resp.json()
            if j.get("ok"):
                QMessageBox.information(None, "注册成功", "注册成功，请返回登录")
                self.return_to_login()
            else:
                QMessageBox.warning(None, "注册失败", j.get("message", "注册失败"))
        else:
            QMessageBox.warning(None, "注册失败", f"HTTP {resp.status_code}")

    def return_to_login(self):
        """
        修改成功后调用，优先通过 test.py 传入的 main_window 引用跳转；
        如果没有传入，再尝试向上查找（作为兜底）。
        """
        # 方式一：直接通过 main_window 引用（推荐）
        if hasattr(self, "main_window") and self.main_window:
            # 如果你在 MainWindow 中实现了 show_login_window()，直接调用它：
            if hasattr(self.main_window, "show_login_window"):
                self.main_window.show_login_window()
            else:
                # 否则直接设置 stacked widget 的当前页
                try:
                    self.main_window.stacked_widget.setCurrentWidget(self.main_window.login_window)
                except Exception as e:
                    QMessageBox.warning(None, "错误", f"无法切换到登录页面：{e}")
            return

        # 方式二：兜底 - 从控件向上查找 QMainWindow（仅在未传 main_window 时使用）
        parent_widget = self.lineEdit
        from PyQt5.QtWidgets import QMainWindow
        while parent_widget is not None:
            parent_widget = parent_widget.parent()
            if parent_widget is None:
                break
            if isinstance(parent_widget, QMainWindow):
                try:
                    # 假设这个 QMainWindow 就是我们的 MainWindow
                    if hasattr(parent_widget, "stacked_widget") and hasattr(parent_widget, "login_window"):
                        parent_widget.stacked_widget.setCurrentWidget(parent_widget.login_window)
                    elif hasattr(parent_widget, "show_login_window"):
                        parent_widget.show_login_window()
                except Exception as e:
                    QMessageBox.warning(None, "错误", f"无法切换到登录页面（兜底失败）：{e}")
                break

